name: CrystalCore
version: ${project.version}
api-version: "1.21"
main: com.crystaltides.core.CrystalCore
author: UltraXn & Antigravity
description: The heart of CrystalTides SMP. Handles linking and web-bridge.
softdepend: [PlaceholderAPI]
load: STARTUP

commands:
  link:
    description: Link your account to the website.
    usage: /link [code]
  unlink:
    description: Unlink your account.
    usage: /unlink
  crystalcore:
    description: Admin commands for CrystalCore.
    permission: crystalcore.admin
    usage: /crystalcore reload
